package com.github.mtailor.test.vttdissector

import com.github.mtailor.common.Vocabulary._
import com.github.mtailor.test.FromClasspathLoader
import com.github.mtailor.util.SubtitleUtil
import org.specs2.mutable.Specification


object VttDissectorSpecs extends Specification with FromClasspathLoader {

  "VttDissector" should {
    "\tparse a tricky vtt file properly" in {
      // this vtt file has stuff like cue headers, blank lines in cues, etc...
      lazy val result = SubtitleUtil.vttToSubtitles(file("vtt_files/sample.vtt"), false)
      result must beEqualTo(SubtitleData.expectedVttFromSample)
    }
    "\tparse a WebVTT file generated by YouTube" in {
      lazy val result = SubtitleUtil.vttToSubtitles(file("vtt_files/sample_youtube.vtt"))
      result mustNotEqual null
      result.length must beGreaterThan(0)
    }
    "\tparse a WebVTT file without header text" in {
      lazy val result = SubtitleUtil.vttToSubtitles(file("vtt_files/sample_no_headers.vtt"))
      result mustNotEqual null
      result.length must beGreaterThan(0)
    }
    "\tde-dupe a WebVTT when we ask it to" in {
      lazy val result = SubtitleUtil.vttToSubtitles(file("vtt_files/sample_youtube.vtt"), true)
      result mustNotEqual null
      result.take(5) must beEqualTo(SubtitleData.expectedFirst5DedupedCaptonsFromYouTubeVttSample)
    }
    "\tDO NOT de-dupe a WebVTT if not specified" in {
      lazy val result = SubtitleUtil.vttToSubtitles(file("vtt_files/sample_youtube.vtt"))
      result mustNotEqual null
      result.take(5) must beEqualTo(SubtitleData.expectedFirst5CaptonsFromYouTubeVttSample)
    }
  }
  
  object SubtitleData {

    val expectedVttFromSample = Seq(
      SubtitleBlock(30, 1610, "I'm the 1st line of subtitle 1\n \nI'm the 3rd line of subtitle 1. The 2nd line had a space and that's all\n".split("\n", -1)),
      SubtitleBlock(1610, 2620, "\nI'm the 2nd line of subtitle 2. The first line was blank and this subtitle also has an optional cue header of '2'\n".split("\n", -1))
    )

    val expectedFirst5CaptonsFromYouTubeVttSample = Seq(
      SubtitleBlock(30, 1610, " \nall<00:00:00.240><c> right</c><00:00:00.480><c> we</c><00:00:00.690><c> are</c><c.colorCCCCCC><00:00:00.719><c> here</c><00:00:01.079><c> in</c><00:00:01.199><c> sunny</c><00:00:01.439><c> Los</c></c>\n".split("\n", -1)),
      SubtitleBlock(1610, 1620, "all right we are<c.colorCCCCCC> here in sunny Los\n </c>\n".split("\n", -1)),
      SubtitleBlock(1620, 3200, "all right we are<c.colorCCCCCC> here in sunny Los\nAngeles<00:00:02.159><c> and</c><00:00:02.370><c> we're</c><00:00:02.610><c> gonna</c><00:00:02.700><c> be</c></c><c.colorE5E5E5><00:00:02.820><c> doing</c><00:00:03.000><c> episode</c></c>\n".split("\n", -1)),
      SubtitleBlock(3200, 3210, "Angeles and we're gonna be<c.colorE5E5E5> doing episode\n </c>\n".split("\n", -1)),
      SubtitleBlock(3210, 6200, "Angeles and we're gonna be<c.colorE5E5E5> doing episode</c>\n<c.colorE5E5E5>on<00:00:03.720><c> pork</c></c><c.colorCCCCCC><00:00:04.500><c> so</c><00:00:04.830><c> we've</c><00:00:04.950><c> done</c><00:00:05.190><c> American</c><00:00:05.940><c> barbecue</c></c>\n".split("\n", -1))

    )
    val expectedFirst5DedupedCaptonsFromYouTubeVttSample = Seq(
      SubtitleBlock(30, 1620, "all<00:00:00.240><c> right</c><00:00:00.480><c> we</c><00:00:00.690><c> are</c><c.colorCCCCCC><00:00:00.719><c> here</c><00:00:01.079><c> in</c><00:00:01.199><c> sunny</c><00:00:01.439><c> Los</c></c>\n".split("\n", -1)),
      SubtitleBlock(1620, 3210, "Angeles<00:00:02.159><c> and</c><00:00:02.370><c> we're</c><00:00:02.610><c> gonna</c><00:00:02.700><c> be</c></c><c.colorE5E5E5><00:00:02.820><c> doing</c><00:00:03.000><c> episode</c></c>\n".split("\n", -1)),
      SubtitleBlock(3210, 6210, "<c.colorE5E5E5>on<00:00:03.720><c> pork</c></c><c.colorCCCCCC><00:00:04.500><c> so</c><00:00:04.830><c> we've</c><00:00:04.950><c> done</c><00:00:05.190><c> American</c><00:00:05.940><c> barbecue</c></c>\n".split("\n", -1)),
      SubtitleBlock(6210, 9450, "<c.colorE5E5E5>pork<00:00:06.990><c> ribs</c></c><c.colorCCCCCC><00:00:07.319><c> before</c></c><c.colorE5E5E5><00:00:07.799><c> oh</c><00:00:08.040><c> yeah</c><00:00:08.309><c> today</c><00:00:08.700><c> we're</c></c>\n".split("\n", -1)),
      SubtitleBlock(9450, 11969, "doing<00:00:09.599><c> pork</c><00:00:10.019><c> Filipino</c><00:00:10.679><c> style</c></c><c.colorCCCCCC><00:00:10.889><c> I</c><00:00:11.219><c> am</c></c><c.colorE5E5E5><00:00:11.280><c> so</c></c>\n".split("\n", -1))
    )
  }
}
